version: "3"
services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.prod
  #   volumes:
  #     - ft_node_modules:/code/node_modules
  #   ports:
  #     - 3000:80


volumes:
  ft_node_modules:

